export interface LanguageConfig {
  code: string;
  name: string;
  nativeName: string;
  direction: 'ltr' | 'rtl';
  ttsAvailable: boolean;
  uiAvailable: boolean;
  sampleAudioText: string;
}

export const SUPPORTED_LANGUAGES: LanguageConfig[] = [
  {
    code: 'en',
    name: 'English',
    nativeName: 'English',
    direction: 'ltr',
    ttsAvailable: true,
    uiAvailable: true,
    sampleAudioText: 'Welcome to AI Health Report Translator.',
  },
  {
    code: 'hi',
    name: 'Hindi',
    nativeName: 'हिन्दी',
    direction: 'ltr',
    ttsAvailable: true,
    uiAvailable: true,
    sampleAudioText: 'एआई स्वास्थ्य रिपोर्ट अनुवादक में आपका स्वागत है।',
  },
  {
    code: 'bn',
    name: 'Bengali',
    nativeName: 'বাংলা',
    direction: 'ltr',
    ttsAvailable: true,
    uiAvailable: true,
    sampleAudioText: 'এআই স্বাস্থ্য রিপোর্ট অনুবাদকে স্বাগতম।',
  },
  {
    code: 'te',
    name: 'Telugu',
    nativeName: 'తెలుగు',
    direction: 'ltr',
    ttsAvailable: true,
    uiAvailable: true,
    sampleAudioText: 'ఏఐ ఆరోగ్య నివేదిక అనువాదకుడికి స్వాగతం.',
  },
  {
    code: 'mr',
    name: 'Marathi',
    nativeName: 'मराठी',
    direction: 'ltr',
    ttsAvailable: true,
    uiAvailable: true,
    sampleAudioText: 'एआय आरोग्य अहवाल अनुवादकामध्ये आपले स्वागत आहे.',
  },
  {
    code: 'ta',
    name: 'Tamil',
    nativeName: 'தமிழ்',
    direction: 'ltr',
    ttsAvailable: true,
    uiAvailable: true,
    sampleAudioText: 'AI சுகாதார அறிக்கை மொழிபெயர்ப்பாளருக்கு வரவேற்கிறோம்.',
  },
  {
    code: 'gu',
    name: 'Gujarati',
    nativeName: 'ગુજરાતી',
    direction: 'ltr',
    ttsAvailable: true,
    uiAvailable: true,
    sampleAudioText: 'એઆઈ આરોગ્ય અહેવાલ અનુવાદકમાં તમારું સ્વાગત છે.',
  },
  {
    code: 'ur',
    name: 'Urdu',
    nativeName: 'اردو',
    direction: 'rtl',
    ttsAvailable: true,
    uiAvailable: true,
    sampleAudioText: 'اے آئی ہیلتھ رپورٹ ٹرانسلیٹر میں خوش آمدید۔',
  },
  {
    code: 'kn',
    name: 'Kannada',
    nativeName: 'ಕನ್ನಡ',
    direction: 'ltr',
    ttsAvailable: true,
    uiAvailable: true,
    sampleAudioText: 'ಎಐ ಆರೋಗ್ಯ ವರದಿ ಅನುವಾದಕಕ್ಕೆ ಸುಸ್ವಾಗತ.',
  },
  {
    code: 'or',
    name: 'Odia',
    nativeName: 'ଓଡ଼ିଆ',
    direction: 'ltr',
    ttsAvailable: true,
    uiAvailable: true,
    sampleAudioText: 'ଏଆଇ ସ୍ୱାସ୍ଥ୍ୟ ରିପୋର୍ଟ ଅନୁବାଦକକୁ ସ୍ୱାଗତ।',
  },
  {
    code: 'ml',
    name: 'Malayalam',
    nativeName: 'മലയാളം',
    direction: 'ltr',
    ttsAvailable: true,
    uiAvailable: true,
    sampleAudioText: 'എഐ ആരോഗ്യ റിപ്പോർട്ട് വിവർത്തകനിലേക്ക് സ്വാഗതം.',
  },
  {
    code: 'pa',
    name: 'Punjabi',
    nativeName: 'ਪੰਜਾਬੀ',
    direction: 'ltr',
    ttsAvailable: true,
    uiAvailable: true,
    sampleAudioText: 'ਏਆਈ ਸਿਹਤ ਰਿਪੋਰਟ ਅਨੁਵਾਦਕ ਵਿੱਚ ਤੁਹਾਡਾ ਸਵਾਗਤ ਹੈ।',
  },
  {
    code: 'as',
    name: 'Assamese',
    nativeName: 'অসমীয়া',
    direction: 'ltr',
    ttsAvailable: true,
    uiAvailable: true,
    sampleAudioText: 'এআই স্বাস্থ্য প্ৰতিবেদন অনুবাদকলৈ স্বাগতম।',
  },
  {
    code: 'mai',
    name: 'Maithili',
    nativeName: 'मैथिली',
    direction: 'ltr',
    ttsAvailable: true,
    uiAvailable: false,
    sampleAudioText: 'एआई स्वास्थ्य रिपोर्ट अनुवादक मे अहाँक स्वागत अछि।',
  },
  {
    code: 'sat',
    name: 'Santali',
    nativeName: 'ᱥᱟᱱᱛᱟᱲᱤ',
    direction: 'ltr',
    ttsAvailable: false,
    uiAvailable: false,
    sampleAudioText: 'ᱮᱟᱭ ᱦᱚᱲᱢᱚ ᱨᱤᱯᱚᱴ ᱛᱚᱨᱡᱚᱢᱟ ᱨᱮ ᱡᱚᱦᱟᱨ᱾',
  },
  {
    code: 'ks',
    name: 'Kashmiri',
    nativeName: 'کٲشُر',
    direction: 'rtl',
    ttsAvailable: false,
    uiAvailable: false,
    sampleAudioText: 'اے آئی صحت رپورٹ ترجمہ کرنس منٛز خوش آمدید۔',
  },
  {
    code: 'ne',
    name: 'Nepali',
    nativeName: 'नेपाली',
    direction: 'ltr',
    ttsAvailable: true,
    uiAvailable: false,
    sampleAudioText: 'एआई स्वास्थ्य रिपोर्ट अनुवादकमा स्वागत छ।',
  },
  {
    code: 'kok',
    name: 'Konkani',
    nativeName: 'कोंकणी',
    direction: 'ltr',
    ttsAvailable: false,
    uiAvailable: false,
    sampleAudioText: 'एआय भलायकी अहवाल भाशांतरकारांत तुमकां येवकार।',
  },
  {
    code: 'sd',
    name: 'Sindhi',
    nativeName: 'سنڌي',
    direction: 'rtl',
    ttsAvailable: false,
    uiAvailable: false,
    sampleAudioText: 'اي آءِ صحت رپورٽ ٽرانسليٽر ۾ ڀلي ڪري آيا.',
  },
  {
    code: 'dog',
    name: 'Dogri',
    nativeName: 'डोगरी',
    direction: 'ltr',
    ttsAvailable: false,
    uiAvailable: false,
    sampleAudioText: 'एआई सेहत रिपोर्ट अनुवादक च थुआड़ा स्वागत ऐ।',
  },
  {
    code: 'mni',
    name: 'Manipuri',
    nativeName: 'মৈতৈলোন্',
    direction: 'ltr',
    ttsAvailable: false,
    uiAvailable: false,
    sampleAudioText: 'AI হকশেলগী পাউদম হন্দোকপদা তরাম্না ওকচরি।',
  },
  {
    code: 'brx',
    name: 'Bodo',
    nativeName: 'बर’',
    direction: 'ltr',
    ttsAvailable: false,
    uiAvailable: false,
    sampleAudioText: 'AI सावस्रि रिपर्ट राव सोलायग्रायाव बरायबाय।',
  },
  {
    code: 'sa',
    name: 'Sanskrit',
    nativeName: 'संस्कृतम्',
    direction: 'ltr',
    ttsAvailable: true,
    uiAvailable: false,
    sampleAudioText: 'एआई स्वास्थ्य प्रतिवेदन अनुवादके स्वागतम्।',
  },
];

export const LANGUAGE_MAP = new Map<string, LanguageConfig>(
  SUPPORTED_LANGUAGES.map((lang) => [lang.code, lang])
);
