"""
Auto-Escalation Engine for Critical Lab Values.
Triggers immediate clinical triage tickets for community health workers.
"""

import uuid
import logging
from typing import List, Optional
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select

from app.models.report import Report
from app.models.patient import Patient
from app.models.health_worker import HealthWorker
from app.models.extracted_value import ExtractedValue
from app.models.escalation import Escalation

logger = logging.getLogger("escalation_manager")


async def handle_report_escalations(
    report: Report,
    extracted_values: List[ExtractedValue],
    db: AsyncSession
) -> List[Escalation]:
    """
    Checks if any extracted value has flag == 'critical'.
    If so, creates an open Escalation ticket for the patient and assigns to an available community health worker.
    """
    critical_values = [v for v in extracted_values if v.flag == "critical"]
    if not critical_values:
        return []

    # Check if escalation already created for this report
    existing_res = await db.execute(select(Escalation).where(Escalation.report_id == report.id))
    existing = existing_res.scalars().all()
    if existing:
        return list(existing)

    # Find patient
    patient_res = await db.execute(select(Patient).where(Patient.id == report.patient_id))
    patient = patient_res.scalar_one_or_none()

    # Find available health workers matching patient language
    hw_res = await db.execute(select(HealthWorker).where(HealthWorker.is_available == True))
    all_hws = hw_res.scalars().all()

    assigned_hw_id = None
    if all_hws:
        patient_lang = patient.preferred_language if patient else "en"
        matching_hws = [hw for hw in all_hws if patient_lang in (hw.languages or [])]
        assigned_hw_id = matching_hws[0].id if matching_hws else all_hws[0].id

    reasons = [
        f"Critical: {v.test_name} measured at {v.value} {v.unit} exceeds emergency panic threshold."
        for v in critical_values
    ]
    combined_reason = " | ".join(reasons)

    escalation = Escalation(
        id=str(uuid.uuid4()),
        report_id=report.id,
        patient_id=report.patient_id,
        reason=combined_reason,
        status="assigned" if assigned_hw_id else "open",
        assigned_to=assigned_hw_id,
        notes=f"Auto-generated by clinical rules engine on report ingestion. {len(critical_values)} panic values flagged.",
    )
    db.add(escalation)
    await db.flush()

    logger.warning(
        f"🚨 Auto-escalation created for Report {report.id} (Patient {report.patient_id}): {combined_reason}"
    )

    return [escalation]
